services:
  backend:
    container_name: backend
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    environment:
      - TZ=Europe/Moscow  # Временная зона
      - APP_PORT=${APP_PORT} # Добавляем переменную для порта
    ports:
      - "8015:${APP_PORT}"
    volumes:
      - ./services/backend:/code:rw  # Для hot-reload кода
    env_file:
      - path: ./services/backend/.env
        required: True
    command: python3 app/main.py