services:
  backend:
    container_name: backend
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    ports:
      - "8015:8015"
    volumes:
      - ./services/backend:./  # Для hot-reload кода
    environment:
      - TZ=Europe/Moscow  # Временная зона
    env_file:
      - path: ./services/backend/.env
        required: True
    command: python3 main.py